from __future__ import annotations

from typing import Any

# Declared structural properties for layout family variants.
# Every pair of variants within a family must differ by at least 2 properties.
LAYOUT_VARIANTS: dict[str, dict[str, dict[str, Any]]] = {
    "book": {
        "book_var_01": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": False,
            "has_page_num": True,
            "has_lines": False,
            "has_frame": False,
            "density": "standard",
            "has_title": True,
        },
        "book_var_02": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": True,
            "has_page_num": True,
            "has_lines": False,
            "has_frame": False,
            "density": "dense",
            "has_title": True,
        },
        "book_var_03": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": True,
            "has_page_num": False,
            "has_lines": True,
            "has_frame": False,
            "density": "dense",
            "has_title": True,
        },
        "book_var_04": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": False,
            "has_page_num": False,
            "has_lines": True,
            "has_frame": False,
            "density": "dense",
            "has_title": True,
        },
        "book_var_05": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": True,
            "has_page_num": True,
            "has_lines": False,
            "has_frame": True,
            "density": "extended",
            "has_title": False,
        },
        "book_var_06": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": False,
            "has_page_num": True,
            "has_lines": False,
            "has_frame": True,
            "density": "extended",
            "has_title": False,
        },
        "book_var_07": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": False,
            "has_page_num": False,
            "has_lines": True,
            "has_frame": True,
            "density": "standard",
            "has_title": False,
        },
        "book_var_08": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": True,
            "has_page_num": False,
            "has_lines": True,
            "has_frame": True,
            "density": "standard",
            "has_title": False,
        },
        "book_var_09": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": False,
            "has_page_num": True,
            "has_lines": True,
            "has_frame": False,
            "density": "dense",
            "has_title": False,
        },
        "book_var_10": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": True,
            "has_page_num": True,
            "has_lines": True,
            "has_frame": False,
            "density": "dense",
            "has_title": False,
        },
        "book_var_11": {
            "orientation": "portrait",
            "columns": 1,
            "has_header": True,
            "has_page_num": False,
            "has_lines": False,
            "has_frame": True,
            "density": "extended",
            "has_title": True,
        },
        "book_var_12": {
            "orientation": "portrait",
            "columns": 2,
            "has_header": False,
            "has_page_num": False,
            "has_lines": False,
            "has_frame": True,
            "density": "extended",
            "has_title": True,
        },
    },
    "official": {
        "official_var_01": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": False,
            "has_attachments": False,
            "has_stamp": False,
            "density": "standard",
            "letterhead_type": "none",
        },
        "official_var_02": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": True,
            "has_approval_resolution": False,
            "has_attachments": False,
            "has_stamp": True,
            "density": "standard",
            "letterhead_type": "none",
        },
        "official_var_03": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": True,
            "has_attachments": False,
            "has_stamp": True,
            "density": "dense",
            "letterhead_type": "none",
        },
        "official_var_04": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": False,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": False,
            "has_attachments": True,
            "has_stamp": False,
            "density": "dense",
            "letterhead_type": "none",
        },
        "official_var_05": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": True,
            "has_approval_resolution": False,
            "has_attachments": True,
            "has_stamp": True,
            "density": "extended",
            "letterhead_type": "none",
        },
        "official_var_06": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": True,
            "has_title": False,
            "has_registration_mark": True,
            "has_approval_resolution": True,
            "has_attachments": False,
            "has_stamp": True,
            "density": "extended",
            "letterhead_type": "angular",
        },
        "official_var_07": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": False,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": False,
            "has_attachments": False,
            "has_stamp": False,
            "density": "standard",
            "letterhead_type": "angular",
        },
        "official_var_08": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": False,
            "has_attachments": True,
            "has_stamp": False,
            "density": "standard",
            "letterhead_type": "longitudinal",
        },
        "official_var_09": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": True,
            "has_approval_resolution": False,
            "has_attachments": False,
            "has_stamp": True,
            "density": "dense",
            "letterhead_type": "longitudinal",
        },
        "official_var_10": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": True,
            "has_title": False,
            "has_registration_mark": False,
            "has_approval_resolution": True,
            "has_attachments": False,
            "has_stamp": True,
            "density": "dense",
            "letterhead_type": "reply",
        },
        "official_var_11": {
            "orientation": "portrait",
            "has_sender_block": False,
            "has_recipient_block": True,
            "has_title": True,
            "has_registration_mark": False,
            "has_approval_resolution": False,
            "has_attachments": True,
            "has_stamp": False,
            "density": "extended",
            "letterhead_type": "reply",
        },
        "official_var_12": {
            "orientation": "portrait",
            "has_sender_block": True,
            "has_recipient_block": False,
            "has_title": True,
            "has_registration_mark": True,
            "has_approval_resolution": False,
            "has_attachments": False,
            "has_stamp": True,
            "density": "extended",
            "letterhead_type": "none",
        },
    },
    "form": {
        "form_var_01": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": False,
            "fields_count": 15,
            "has_stamp_safe": False,
            "has_lines": False,
            "has_frame": False,
            "has_header": False,
            "density": "standard",
        },
        "form_var_02": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": True,
            "fields_count": 25,
            "has_stamp_safe": True,
            "has_lines": True,
            "has_frame": True,
            "has_header": True,
            "density": "dense",
        },
        "form_var_03": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": True,
            "fields_count": 35,
            "has_stamp_safe": False,
            "has_lines": True,
            "has_frame": False,
            "has_header": True,
            "density": "extended",
        },
        "form_var_04": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": False,
            "fields_count": 15,
            "has_stamp_safe": True,
            "has_lines": False,
            "has_frame": True,
            "has_header": False,
            "density": "standard",
        },
        "form_var_05": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": True,
            "fields_count": 25,
            "has_stamp_safe": True,
            "has_lines": False,
            "has_frame": True,
            "has_header": True,
            "density": "dense",
        },
        "form_var_06": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": True,
            "fields_count": 15,
            "has_stamp_safe": False,
            "has_lines": True,
            "has_frame": False,
            "has_header": False,
            "density": "extended",
        },
        "form_var_07": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": False,
            "fields_count": 35,
            "has_stamp_safe": True,
            "has_lines": True,
            "has_frame": True,
            "has_header": False,
            "density": "standard",
        },
        "form_var_08": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": False,
            "fields_count": 25,
            "has_stamp_safe": False,
            "has_lines": False,
            "has_frame": False,
            "has_header": True,
            "density": "dense",
        },
        "form_var_09": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": True,
            "fields_count": 15,
            "has_stamp_safe": False,
            "has_lines": True,
            "has_frame": True,
            "has_header": False,
            "density": "extended",
        },
        "form_var_10": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": False,
            "fields_count": 35,
            "has_stamp_safe": False,
            "has_lines": False,
            "has_frame": False,
            "has_header": True,
            "density": "standard",
        },
        "form_var_11": {
            "orientation": "portrait",
            "has_instruction_block": False,
            "has_group_2": True,
            "fields_count": 25,
            "has_stamp_safe": False,
            "has_lines": True,
            "has_frame": False,
            "has_header": False,
            "density": "dense",
        },
        "form_var_12": {
            "orientation": "portrait",
            "has_instruction_block": True,
            "has_group_2": True,
            "fields_count": 35,
            "has_stamp_safe": True,
            "has_lines": False,
            "has_frame": True,
            "has_header": True,
            "density": "extended",
        },
    },
    "table": {
        "table_var_01": {
            "columns_count": 5,
            "rows_count": 30,
            "has_note": False,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": True,
            "density": "dense",
            "orientation": "portrait",
        },
        "table_var_02": {
            "columns_count": 7,
            "rows_count": 20,
            "has_note": True,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": False,
            "density": "extended",
            "orientation": "portrait",
        },
        "table_var_03": {
            "columns_count": 5,
            "rows_count": 30,
            "has_note": False,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": True,
            "density": "extended",
            "orientation": "portrait",
        },
        "table_var_04": {
            "columns_count": 5,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": True,
            "has_frame": False,
            "density": "dense",
            "orientation": "portrait",
        },
        "table_var_05": {
            "columns_count": 5,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": True,
            "has_lines": False,
            "has_stamp": True,
            "has_frame": False,
            "density": "standard",
            "orientation": "portrait",
        },
        "table_var_06": {
            "columns_count": 3,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": True,
            "density": "extended",
            "orientation": "portrait",
        },
        "table_var_07": {
            "columns_count": 3,
            "rows_count": 10,
            "has_note": False,
            "has_page_num": True,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": True,
            "density": "extended",
            "orientation": "portrait",
        },
        "table_var_08": {
            "columns_count": 3,
            "rows_count": 30,
            "has_note": True,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": True,
            "density": "standard",
            "orientation": "portrait",
        },
        "table_var_09": {
            "columns_count": 7,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": False,
            "density": "standard",
            "orientation": "portrait",
        },
        "table_var_10": {
            "columns_count": 5,
            "rows_count": 10,
            "has_note": False,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": True,
            "density": "extended",
            "orientation": "portrait",
        },
        "table_var_11": {
            "columns_count": 5,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": True,
            "density": "dense",
            "orientation": "portrait",
        },
        "table_var_12": {
            "columns_count": 3,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": True,
            "has_frame": True,
            "density": "dense",
            "orientation": "portrait",
        },
        "table_var_13": {
            "columns_count": 5,
            "rows_count": 20,
            "has_note": True,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": True,
            "has_frame": True,
            "density": "dense",
            "orientation": "landscape",
        },
        "table_var_14": {
            "columns_count": 5,
            "rows_count": 10,
            "has_note": True,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": True,
            "density": "extended",
            "orientation": "landscape",
        },
        "table_var_15": {
            "columns_count": 7,
            "rows_count": 15,
            "has_note": True,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": True,
            "has_frame": True,
            "density": "extended",
            "orientation": "landscape",
        },
        "table_var_16": {
            "columns_count": 5,
            "rows_count": 15,
            "has_note": False,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": True,
            "has_frame": False,
            "density": "standard",
            "orientation": "landscape",
        },
        "table_var_17": {
            "columns_count": 7,
            "rows_count": 10,
            "has_note": True,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": True,
            "has_frame": False,
            "density": "standard",
            "orientation": "landscape",
        },
        "table_var_18": {
            "columns_count": 7,
            "rows_count": 20,
            "has_note": True,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": True,
            "has_frame": True,
            "density": "standard",
            "orientation": "landscape",
        },
        "table_var_19": {
            "columns_count": 7,
            "rows_count": 20,
            "has_note": True,
            "has_page_num": True,
            "has_lines": False,
            "has_stamp": True,
            "has_frame": True,
            "density": "extended",
            "orientation": "landscape",
        },
        "table_var_20": {
            "columns_count": 7,
            "rows_count": 15,
            "has_note": True,
            "has_page_num": False,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": False,
            "density": "dense",
            "orientation": "landscape",
        },
        "table_var_21": {
            "columns_count": 7,
            "rows_count": 15,
            "has_note": False,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": False,
            "density": "standard",
            "orientation": "landscape",
        },
        "table_var_22": {
            "columns_count": 3,
            "rows_count": 10,
            "has_note": False,
            "has_page_num": True,
            "has_lines": True,
            "has_stamp": True,
            "has_frame": True,
            "density": "dense",
            "orientation": "landscape",
        },
        "table_var_23": {
            "columns_count": 7,
            "rows_count": 15,
            "has_note": True,
            "has_page_num": True,
            "has_lines": False,
            "has_stamp": False,
            "has_frame": False,
            "density": "standard",
            "orientation": "landscape",
        },
        "table_var_24": {
            "columns_count": 3,
            "rows_count": 20,
            "has_note": False,
            "has_page_num": False,
            "has_lines": True,
            "has_stamp": False,
            "has_frame": False,
            "density": "extended",
            "orientation": "landscape",
        },
    },
    "specialized": {
        "spec_var_01": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": False,
            "has_header": False,
            "has_footer": True,
            "has_sidebar": False,
            "columns": 1,
            "density": "standard",
            "has_signature": True,
        },
        "spec_var_02": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": True,
            "has_header": True,
            "has_footer": True,
            "has_sidebar": False,
            "columns": 2,
            "density": "dense",
            "has_signature": True,
        },
        "spec_var_03": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": True,
            "has_header": True,
            "has_footer": False,
            "has_sidebar": True,
            "columns": 3,
            "density": "extended",
            "has_signature": False,
        },
        "spec_var_04": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": False,
            "has_header": False,
            "has_footer": False,
            "has_sidebar": True,
            "columns": 1,
            "density": "standard",
            "has_signature": False,
        },
        "spec_var_05": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": True,
            "has_header": True,
            "has_footer": True,
            "has_sidebar": True,
            "columns": 2,
            "density": "dense",
            "has_signature": True,
        },
        "spec_var_06": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": True,
            "has_header": False,
            "has_footer": False,
            "has_sidebar": False,
            "columns": 3,
            "density": "extended",
            "has_signature": False,
        },
        "spec_var_07": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": False,
            "has_header": True,
            "has_footer": True,
            "has_sidebar": True,
            "columns": 1,
            "density": "standard",
            "has_signature": True,
        },
        "spec_var_08": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": True,
            "has_header": True,
            "has_footer": False,
            "has_sidebar": False,
            "columns": 2,
            "density": "dense",
            "has_signature": False,
        },
        "spec_var_09": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": False,
            "has_header": False,
            "has_footer": True,
            "has_sidebar": True,
            "columns": 3,
            "density": "extended",
            "has_signature": True,
        },
        "spec_var_10": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": False,
            "has_header": True,
            "has_footer": False,
            "has_sidebar": False,
            "columns": 1,
            "density": "standard",
            "has_signature": True,
        },
        "spec_var_11": {
            "orientation": "portrait",
            "has_stamp": False,
            "has_separator": True,
            "has_header": False,
            "has_footer": True,
            "has_sidebar": False,
            "columns": 2,
            "density": "dense",
            "has_signature": False,
        },
        "spec_var_12": {
            "orientation": "portrait",
            "has_stamp": True,
            "has_separator": False,
            "has_header": True,
            "has_footer": True,
            "has_sidebar": True,
            "columns": 3,
            "density": "extended",
            "has_signature": True,
        },
    },
    "reference": {
        "ref_var_01": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": False,
            "has_lines": False,
            "has_frame": False,
            "has_page_num": True,
            "density": "standard",
            "has_header": False,
        },
        "ref_var_02": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": True,
            "has_lines": True,
            "has_frame": True,
            "has_page_num": True,
            "density": "dense",
            "has_header": True,
        },
        "ref_var_03": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": False,
            "has_lines": True,
            "has_frame": False,
            "has_page_num": False,
            "density": "extended",
            "has_header": True,
        },
        "ref_var_04": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": True,
            "has_lines": False,
            "has_frame": True,
            "has_page_num": False,
            "density": "standard",
            "has_header": False,
        },
        "ref_var_05": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": True,
            "has_lines": False,
            "has_frame": True,
            "has_page_num": True,
            "density": "dense",
            "has_header": False,
        },
        "ref_var_06": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": False,
            "has_lines": True,
            "has_frame": False,
            "has_page_num": True,
            "density": "extended",
            "has_header": False,
        },
        "ref_var_07": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": False,
            "has_lines": True,
            "has_frame": True,
            "has_page_num": False,
            "density": "standard",
            "has_header": True,
        },
        "ref_var_08": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": True,
            "has_lines": True,
            "has_frame": False,
            "has_page_num": False,
            "density": "dense",
            "has_header": False,
        },
        "ref_var_09": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": True,
            "has_lines": True,
            "has_frame": True,
            "has_page_num": True,
            "density": "extended",
            "has_header": True,
        },
        "ref_var_10": {
            "orientation": "portrait",
            "columns": 2,
            "has_range": False,
            "has_lines": False,
            "has_frame": False,
            "has_page_num": True,
            "density": "standard",
            "has_header": True,
        },
        "ref_var_11": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": True,
            "has_lines": False,
            "has_frame": False,
            "has_page_num": False,
            "density": "dense",
            "has_header": False,
        },
        "ref_var_12": {
            "orientation": "portrait",
            "columns": 1,
            "has_range": False,
            "has_lines": True,
            "has_frame": True,
            "has_page_num": False,
            "density": "extended",
            "has_header": False,
        },
    },
    "structured": {
        "struct_var_01": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": False,
            "has_masthead": False,
            "has_issue_metadata": False,
            "has_footer_note": True,
            "has_lines": False,
            "density": "standard",
        },
        "struct_var_02": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": True,
            "has_masthead": True,
            "has_issue_metadata": True,
            "has_footer_note": True,
            "has_lines": True,
            "density": "dense",
        },
        "struct_var_03": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": True,
            "has_masthead": False,
            "has_issue_metadata": True,
            "has_footer_note": False,
            "has_lines": True,
            "density": "extended",
        },
        "struct_var_04": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": False,
            "has_masthead": True,
            "has_issue_metadata": False,
            "has_footer_note": False,
            "has_lines": False,
            "density": "standard",
        },
        "struct_var_05": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": True,
            "has_masthead": True,
            "has_issue_metadata": True,
            "has_footer_note": False,
            "has_lines": False,
            "density": "dense",
        },
        "struct_var_06": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": False,
            "has_masthead": False,
            "has_issue_metadata": True,
            "has_footer_note": True,
            "has_lines": True,
            "density": "extended",
        },
        "struct_var_07": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": False,
            "has_masthead": True,
            "has_issue_metadata": False,
            "has_footer_note": True,
            "has_lines": True,
            "density": "standard",
        },
        "struct_var_08": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": True,
            "has_masthead": False,
            "has_issue_metadata": False,
            "has_footer_note": False,
            "has_lines": False,
            "density": "dense",
        },
        "struct_var_09": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": False,
            "has_masthead": False,
            "has_issue_metadata": True,
            "has_footer_note": True,
            "has_lines": False,
            "density": "extended",
        },
        "struct_var_10": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": True,
            "has_masthead": True,
            "has_issue_metadata": False,
            "has_footer_note": False,
            "has_lines": True,
            "density": "standard",
        },
        "struct_var_11": {
            "orientation": "portrait",
            "columns": 2,
            "has_lead_story": True,
            "has_masthead": False,
            "has_issue_metadata": True,
            "has_footer_note": True,
            "has_lines": False,
            "density": "dense",
        },
        "struct_var_12": {
            "orientation": "portrait",
            "columns": 3,
            "has_lead_story": False,
            "has_masthead": True,
            "has_issue_metadata": True,
            "has_footer_note": False,
            "has_lines": True,
            "density": "extended",
        },
    },
}


def get_variant_properties(family: str, variant_id: str) -> dict[str, Any]:
    """Retrieve structural properties for a given family and variant ID."""
    family_variants = LAYOUT_VARIANTS.get(family, {})
    return family_variants.get(variant_id, {})


def choose_variant(family: str, orientation: str, seed: int) -> str:
    """Deterministically choose a variant matching the family and orientation."""
    family_variants = LAYOUT_VARIANTS.get(family, {})
    matching = [
        vid
        for vid, props in family_variants.items()
        if props.get("orientation") == orientation
    ]
    if not matching:
        # Fallback to all variants if no orientation match
        matching = list(family_variants.keys())
    if not matching:
        return "default"
    # Stable selection using seed
    return matching[seed % len(matching)]
